In [2]:
import pandas as pd

In [3]:
# load the Dataset 
df =pd.read_csv("dataset_Facebook.csv")

In [4]:
df.head()

,url,post_id,post_url,comment_id,user_name,user_id,user_url,date_created,comment_text,num_likes,num_replies,attached_files,video_length,source_type,subtype,type
0,https://www.facebook.com/verizon/posts/pfbid0z...,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,https://www.facebook.com/verizon/posts/pfbid0z...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...,Kat███Dav███on,pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...,NaN,"""2024-01-12T13:41:08.000Z""",Joy House,NaN,1.0,NaN,NaN,TextWithEntities,TextWithEntities,Comment
1,https://www.facebook.com/verizon/posts/pfbid0z...,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,https://www.facebook.com/verizon/posts/pfbid0z...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzE2MjYyOTc0Nz...,Jam███McI███re,pfbid02DAD4uXif7L2ibVx7zZ4B8vbza7Tqrqzdn1kF3T1...,https://www.facebook.com/JmyMck,"""2024-01-19T22:33:51.000Z""",Yet if a Verizon customer travels outside of t...,NaN,1.0,NaN,NaN,TextWithEntities,TextWithEntities,Comment
2,https://www.facebook.com/verizon/posts/pfbid0z...,pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...,https://www.facebook.com/verizon/posts/pfbid0z...,Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTE0MTkxMTI2Nz...,Bub███Bug███,pfbid02DVKaLESKQqoYHcmo2HeMBuUs2JNK18KZDMa1hML...,NaN,"""2024-01-16T01:39:54.000Z""",Where is the 5g we was promised 2 years ago,NaN,1.0,NaN,NaN,TextWithEntities,TextWithEntities,Comment
3,https://www.facebook.com/reel/260478723678355?...,260478723678355,https://www.facebook.com/reel/260478723678355?...,Y29tbWVudDo3NTY0MDE0ODY1MjY5MTJfMTA3NDgyMzY5Mz...,Dan███uth███,pfbid0WfY4JxPXbR2Xp4tsUCaaVtwGqwArAbCEL3BM7QXS...,https://www.facebook.com/danrouthphoto,"""2024-02-06T02:46:19.000Z""",Your customer service may be the worst on eart...,NaN,1.0,NaN,NaN,TextWithEntities,TextWithEntities,Comment
4,https://www.facebook.com/3newsgh/posts/pfbid02...,pfbid02dTZDs29765oxhxyV6s3Pmzeq2H8XPEeiCdaZiAj...,https://www.facebook.com/3newsgh/posts/pfbid02...,Y29tbWVudDo4NjcyMzM5MzU1NzMzMjNfNTUwNjE4MzI3Nz...,Mus███Ali███nne███,100004055062562,https://www.facebook.com/musahali.traore,"""2024-11-28T08:40:43.000Z""",And what does this picture suppose to mean? Th...,NaN,1.0,NaN,NaN,TextWithEntities,TextWithEntities,Comment

In [5]:
# Basics of the Info about the Visulaitaion 
print( df.columns)
print(df.info())
print( df.describe())

Index(['url', 'post_id', 'post_url', 'comment_id', 'user_name', 'user_id',
       'user_url', 'date_created', 'comment_text', 'num_likes', 'num_replies',
       'attached_files', 'video_length', 'source_type', 'subtype', 'type'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             1000 non-null   object
 1   post_id         1000 non-null   object
 2   post_url        1000 non-null   object
 3   comment_id      1000 non-null   object
 4   user_name       1000 non-null   object
 5   user_id         1000 non-null   object
 6   user_url        408 non-null    object
 7   date_created    1000 non-null   object
 8   comment_text    964 non-null    object
 9   num_likes       0 non-null      float64
 10  num_replies     398 non-null    float64
 11  attached_files  90 non-null     object
 12  video_length    0 non-null      float64
 13  source_type     964 non-null    object
 14  subtype         964 non-null    object
 15  type            1000 non-null   object
dtypes: float64(3), object(13)
memory usage: 125.1+ KB
None
       num_likes  num_replies  video_length
count        0.0   398.000000           0.0
mean         NaN     2.711055           NaN
std          NaN     3.460381           NaN
min          NaN     1.000000           NaN
25%          NaN     1.000000           NaN
50%          NaN     2.000000           NaN
75%          NaN     3.000000           NaN
max          NaN    39.000000           NaN

In [6]:
# 3) Data Subsets 
# Columns Subset 
subset = df[['user_id' , 'user_name']]
print(subset.head())

                                             user_id           user_name
0  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      Kat███Dav███on
1  pfbid02DAD4uXif7L2ibVx7zZ4B8vbza7Tqrqzdn1kF3T1...      Jam███McI███re
2  pfbid02DVKaLESKQqoYHcmo2HeMBuUs2JNK18KZDMa1hML...        Bub███Bug███
3  pfbid0WfY4JxPXbR2Xp4tsUCaaVtwGqwArAbCEL3BM7QXS...        Dan███uth███
4                                    100004055062562  Mus███Ali███nne███

In [7]:
# row Filter 
high_likes = df[df['num_replies'] > 18]
print(high_likes.head)

<bound method NDFrame.head of                                                    url  \
394  https://www.facebook.com/reel/883246459887168?...
395  https://www.facebook.com/reel/538446054970035?...
396  https://www.facebook.com/reel/883246459887168?...
397  https://www.facebook.com/verizon/posts/pfbid0z...

                                               post_id  \
394                                    883246459887168
395                                    538446054970035
396                                    883246459887168
397  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...

                                              post_url  \
394  https://www.facebook.com/reel/883246459887168?...
395  https://www.facebook.com/reel/538446054970035?...
396  https://www.facebook.com/reel/883246459887168?...
397  https://www.facebook.com/verizon/posts/pfbid0z...

                                            comment_id  \
394  Y29tbWVudDo3MTQ0MDI4MjczOTM0NDVfMTI2MDk1MTI2Nz...
395  Y29tbWVudDoxMDE2MDAyNjQ1ODA5NzMzNF80OTE2Njk0ND...
396  Y29tbWVudDo3MTQ0MDI4MjczOTM0NDVfMzMzMjgwNTY1OD...
397  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzI3NDAyNjUwMj...

                    user_name  \
394             Mic███l S███e
395  Lyn███Har███on █████████
396             Mic███l S███e
397        Son███L. ███gel███

                                               user_id  \
394  pfbid0J4NhsL5VzvbqCekLBTitBksSo7NJRdXUMVDshJZg...
395  pfbid0Zzwvh7fVaD8L8H2tys6yHFvgtNBG31Fs34jC8zzZ...
396  pfbid0J4NhsL5VzvbqCekLBTitBksSo7NJRdXUMVDshJZg...
397  pfbid02ibbm7GtH5axzJJCpgoj3mcgJzUhP8rAtpC9DjzF...

                                              user_url  \
394  https://www.facebook.com/people/Michael-Stone/...
395     https://www.facebook.com/lynda.harrisonhornsby
396  https://www.facebook.com/people/Michael-Stone/...
397                                                NaN

                   date_created  \
394  "2023-09-21T19:30:51.000Z"
395  "2023-01-23T01:26:22.000Z"
396  "2023-09-21T19:30:53.000Z"
397  "2024-01-14T04:00:22.000Z"

                                          comment_text  num_likes  \
394  Got new devices recently was told the bill wou...        NaN
395  I’m making the switch from AT&T!! I’m tired of...        NaN
396  Spent 3 hours talking to an agent came down to...        NaN
397  No service what so ever when I used to get per...        NaN

     num_replies attached_files  video_length       source_type  \
394         19.0            NaN           NaN  TextWithEntities
395         19.0            NaN           NaN  TextWithEntities
396         24.0            NaN           NaN  TextWithEntities
397         39.0            NaN           NaN  TextWithEntities

              subtype     type
394  TextWithEntities  Comment
395  TextWithEntities  Comment
396  TextWithEntities  Comment
397  TextWithEntities  Comment  >

In [8]:
# loc(label based )--> give the data from the 3rd index to the 5 th index 
df.loc[3:5,['num_replies' , 'user_id']]

   num_replies                                            user_id
3          1.0  pfbid0WfY4JxPXbR2Xp4tsUCaaVtwGqwArAbCEL3BM7QXS...
4          1.0                                    100004055062562
5          1.0                                         1363782034

In [9]:
# iloc = integer location based indexing

#  It selects data using row index numbers and column index numbers
# 1️⃣ 0:5 → Rows
# Start from row index 0
# Go up to (but not include) 5

# 👉 Selected rows:

# 0, 1, 2, 3, 4   ✅ (5 rows total)
# 2️⃣ 0:2 → Columns
# Start from column index 0
# Go up to (but not include) 2

# 👉 Selected columns:

# 0, 1   ✅ (2 columns total)
print(df.iloc[0:3 , 0 :3])

                                                 url  \
0  https://www.facebook.com/verizon/posts/pfbid0z...
1  https://www.facebook.com/verizon/posts/pfbid0z...
2  https://www.facebook.com/verizon/posts/pfbid0z...

                                             post_id  \
0  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
1  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
2  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...

                                            post_url
0  https://www.facebook.com/verizon/posts/pfbid0z...
1  https://www.facebook.com/verizon/posts/pfbid0z...
2  https://www.facebook.com/verizon/posts/pfbid0z...

In [10]:
#Sorting the Data 
sorted_df = df.sort_values(by='num_replies' , ascending= False)
print(sorted_df.head(5))

                                                   url  \
397  https://www.facebook.com/verizon/posts/pfbid0z...
396  https://www.facebook.com/reel/883246459887168?...
395  https://www.facebook.com/reel/538446054970035?...
394  https://www.facebook.com/reel/883246459887168?...
393  https://www.facebook.com/verizon/videos/183827...

                                               post_id  \
397  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
396                                    883246459887168
395                                    538446054970035
394                                    883246459887168
393                                   1838276870026879

                                              post_url  \
397  https://www.facebook.com/verizon/posts/pfbid0z...
396  https://www.facebook.com/reel/883246459887168?...
395  https://www.facebook.com/reel/538446054970035?...
394  https://www.facebook.com/reel/883246459887168?...
393  https://www.facebook.com/verizon/videos/183827...

                                            comment_id  \
397  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzI3NDAyNjUwMj...
396  Y29tbWVudDo3MTQ0MDI4MjczOTM0NDVfMzMzMjgwNTY1OD...
395  Y29tbWVudDoxMDE2MDAyNjQ1ODA5NzMzNF80OTE2Njk0ND...
394  Y29tbWVudDo3MTQ0MDI4MjczOTM0NDVfMTI2MDk1MTI2Nz...
393  Y29tbWVudDo0MTEyNjQ1MDEyODgzNzZfMTYwNjMxMTI5Nj...

                    user_name  \
397        Son███L. ███gel███
396             Mic███l S███e
395  Lyn███Har███on █████████
394             Mic███l S███e
393              Ter███Dan███

                                               user_id  \
397  pfbid02ibbm7GtH5axzJJCpgoj3mcgJzUhP8rAtpC9DjzF...
396  pfbid0J4NhsL5VzvbqCekLBTitBksSo7NJRdXUMVDshJZg...
395  pfbid0Zzwvh7fVaD8L8H2tys6yHFvgtNBG31Fs34jC8zzZ...
394  pfbid0J4NhsL5VzvbqCekLBTitBksSo7NJRdXUMVDshJZg...
393                                    100004164335053

                                              user_url  \
397                                                NaN
396  https://www.facebook.com/people/Michael-Stone/...
395     https://www.facebook.com/lynda.harrisonhornsby
394  https://www.facebook.com/people/Michael-Stone/...
393  https://www.facebook.com/people/Terry-Danley/1...

                   date_created  \
397  "2024-01-14T04:00:22.000Z"
396  "2023-09-21T19:30:53.000Z"
395  "2023-01-23T01:26:22.000Z"
394  "2023-09-21T19:30:51.000Z"
393  "2024-02-07T02:19:53.000Z"

                                          comment_text  num_likes  \
397  No service what so ever when I used to get per...        NaN
396  Spent 3 hours talking to an agent came down to...        NaN
395  I’m making the switch from AT&T!! I’m tired of...        NaN
394  Got new devices recently was told the bill wou...        NaN
393  Verizon.  Is telling me the replacement phone ...        NaN

     num_replies                                     attached_files  \
397         39.0                                                NaN
396         24.0                                                NaN
395         19.0                                                NaN
394         19.0                                                NaN
393         18.0  ["https://www.facebook.com/photo.php?fbid=2767...

     video_length       source_type           subtype     type
397           NaN  TextWithEntities  TextWithEntities  Comment
396           NaN  TextWithEntities  TextWithEntities  Comment
395           NaN  TextWithEntities  TextWithEntities  Comment
394           NaN  TextWithEntities  TextWithEntities  Comment
393           NaN  TextWithEntities  TextWithEntities  Comment

In [11]:
# Transpose the Data 
transpose_df = df.T
print(transpose_df)

                                                              0    \
url             https://www.facebook.com/verizon/posts/pfbid0z...
post_id         pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
post_url        https://www.facebook.com/verizon/posts/pfbid0z...
comment_id      Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...
user_name                                          Kat███Dav███on
user_id         pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...
user_url                                                      NaN
date_created                           "2024-01-12T13:41:08.000Z"
comment_text                                            Joy House
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              1    \
url             https://www.facebook.com/verizon/posts/pfbid0z...
post_id         pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
post_url        https://www.facebook.com/verizon/posts/pfbid0z...
comment_id      Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzE2MjYyOTc0Nz...
user_name                                          Jam███McI███re
user_id         pfbid02DAD4uXif7L2ibVx7zZ4B8vbza7Tqrqzdn1kF3T1...
user_url                          https://www.facebook.com/JmyMck
date_created                           "2024-01-19T22:33:51.000Z"
comment_text    Yet if a Verizon customer travels outside of t...
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              2    \
url             https://www.facebook.com/verizon/posts/pfbid0z...
post_id         pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
post_url        https://www.facebook.com/verizon/posts/pfbid0z...
comment_id      Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTE0MTkxMTI2Nz...
user_name                                            Bub███Bug███
user_id         pfbid02DVKaLESKQqoYHcmo2HeMBuUs2JNK18KZDMa1hML...
user_url                                                      NaN
date_created                           "2024-01-16T01:39:54.000Z"
comment_text          Where is the 5g we was promised 2 years ago
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              3    \
url             https://www.facebook.com/reel/260478723678355?...
post_id                                           260478723678355
post_url        https://www.facebook.com/reel/260478723678355?...
comment_id      Y29tbWVudDo3NTY0MDE0ODY1MjY5MTJfMTA3NDgyMzY5Mz...
user_name                                            Dan███uth███
user_id         pfbid0WfY4JxPXbR2Xp4tsUCaaVtwGqwArAbCEL3BM7QXS...
user_url                   https://www.facebook.com/danrouthphoto
date_created                           "2024-02-06T02:46:19.000Z"
comment_text    Your customer service may be the worst on eart...
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              4    \
url             https://www.facebook.com/3newsgh/posts/pfbid02...
post_id         pfbid02dTZDs29765oxhxyV6s3Pmzeq2H8XPEeiCdaZiAj...
post_url        https://www.facebook.com/3newsgh/posts/pfbid02...
comment_id      Y29tbWVudDo4NjcyMzM5MzU1NzMzMjNfNTUwNjE4MzI3Nz...
user_name                                      Mus███Ali███nne███
user_id                                           100004055062562
user_url                 https://www.facebook.com/musahali.traore
date_created                           "2024-11-28T08:40:43.000Z"
comment_text    And what does this picture suppose to mean? Th...
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              5    \
url             https://www.facebook.com/attbusiness/videos/35...
post_id                                          3587754878110674
post_url        https://www.facebook.com/attbusiness/videos/35...
comment_id      Y29tbWVudDoxMDE1OTk4MTE2NTAzNzMzNF8zNTM3MDA5ND...
user_name                                            Pat███Pol███
user_id                                                1363782034
user_url                    https://www.facebook.com/patti.polk.9
date_created                           "2023-10-31T18:38:04.000Z"
comment_text                                            AT&T - ty
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              6    \
url             https://www.facebook.com/reel/260478723678355?...
post_id                                           260478723678355
post_url        https://www.facebook.com/reel/260478723678355?...
comment_id      Y29tbWVudDo3NTY0MDE0ODY1MjY5MTJfOTE2NjUyNTAwMT...
user_name                                            Tom███ark███
user_id                                           100073728533089
user_url        https://www.facebook.com/people/Tom-Clark/1000...
date_created                           "2024-03-04T14:43:56.000Z"
comment_text                                       Makes no sense
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              7    \
url             https://www.facebook.com/attbusiness/videos/55...
post_id                                           556616592556942
post_url        https://www.facebook.com/attbusiness/videos/55...
comment_id      Y29tbWVudDoxMDE1OTk4Mjc5MDMwMjMzNF82OTMzMjc4MT...
user_name                                   Lis███enn███ In██████
user_id         pfbid0g7mhRaoFr97FQ3g1z3GSA33y9jKGYJyaM1CPH3Hm...
user_url                                                      NaN
date_created                           "2023-03-16T15:31:36.000Z"
comment_text    ATT Business customer service is HORRIBLE!  Ta...
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              8    \
url             https://www.facebook.com/reel/260478723678355?...
post_id                                           260478723678355
post_url        https://www.facebook.com/reel/260478723678355?...
comment_id      Y29tbWVudDo3NTY0MDE0ODY1MjY5MTJfMzAyNjY2MTc5ND...
user_name                                           Sar███Bea███n
user_id                                                1558253528
user_url                                                      NaN
date_created                           "2024-02-20T13:12:51.000Z"
comment_text               You suck #period #customerserviceblows
num_likes                                                     NaN
num_replies                                                   1.0
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              9    ...  \
url             https://www.facebook.com/attbusiness/videos/50...  ...
post_id                                           507615747875909  ...
post_url        https://www.facebook.com/attbusiness/videos/50...  ...
comment_id      Y29tbWVudDoxMDE2MDAwOTgxMjc3MjMzNF81OTk5MzkzMT...  ...
user_name                                           Geo███ Ma███n  ...
user_id         pfbid037DyeqVtsTVCaTMDsjkKAfivJAkF95BZZEE1XFKm...  ...
user_url                                                      NaN  ...
date_created                           "2023-02-15T18:11:09.000Z"  ...
comment_text    Why did AT&T/Direct TV remove non Liberal stat...  ...
num_likes                                                     NaN  ...
num_replies                                                   1.0  ...
attached_files                                                NaN  ...
video_length                                                  NaN  ...
source_type                                      TextWithEntities  ...
subtype                                          TextWithEntities  ...
type                                                      Comment  ...

                                                              990  \
url             https://www.facebook.com/attbusiness/videos/57...
post_id                                          5719366298153202
post_url        https://www.facebook.com/attbusiness/videos/57...
comment_id      Y29tbWVudDoxMDE1OTk5NTcxOTI0NzMzNF8xMzA4OTkwOT...
user_name                                            Pat███Pol███
user_id                                                1363782034
user_url                    https://www.facebook.com/patti.polk.9
date_created                           "2023-10-31T18:37:52.000Z"
comment_text    AT&T - I bought the new 15 and it’s been in a ...
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              991  \
url             https://www.facebook.com/verizon/posts/pfbid0z...
post_id         pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
post_url        https://www.facebook.com/verizon/posts/pfbid0z...
comment_id      Y29tbWVudDozOTczNzM0OTkzNDQxNDNfMzE5NjczNTAwNz...
user_name                                           Cas███ Su███r
user_id         pfbid03faAGuF9hjaT7xJpy4qPiX2EoDbDJdg6qJdut6D2...
user_url                                                      NaN
date_created                           "2024-01-12T11:49:46.000Z"
comment_text                             Gretchen Esselstein 🤣🤣🤣🤣
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              992  \
url             https://www.facebook.com/lisabacabookkeeping/p...
post_id         pfbid025GHhdZv9FwPzPQcYvw8p5DNbFKGxiLtPSRrKvPp...
post_url        https://www.facebook.com/lisabacabookkeeping/p...
comment_id      Y29tbWVudDo0NzcwOTUzNjQyOTQyNTk3XzQ3NzA5NTg2Nz...
user_name                                            Lee███ Ga███
user_id         pfbid02P2MtrYR2gHp8JX2z5qpbCArU9br2grTdW3TB458...
user_url                                                      NaN
date_created                           "2022-02-25T03:27:47.000Z"
comment_text                  Oh this melts my heart!! Love it ❤❤
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              993  \
url             https://www.facebook.com/lisabacabookkeeping/p...
post_id         pfbid02GftBE6TjUxZLo3gkkSsPibBtq4mwDnYRNnHcnrh...
post_url        https://www.facebook.com/lisabacabookkeeping/p...
comment_id      Y29tbWVudDo0NDk3ODEwMDMwMjU2OTYxXzQ0OTc5Nzc2OD...
user_name                                            Lex███ose███
user_id         pfbid0JhcfQSSeaCMagS2f4oiJUXRGsU3cRwE4jBRkmXC6...
user_url                                                      NaN
date_created                           "2021-12-11T17:08:37.000Z"
comment_text                  She is incredible! So proud of her!
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              994  \
url             https://www.facebook.com/shanklinhvac/videos/1...
post_id                                          1035709791487472
post_url        https://www.facebook.com/shanklinhvac/videos/1...
comment_id      Y29tbWVudDoxMjc3NTIwNzYzNTU0MjI2Xzg0Njc5MTc0MD...
user_name                                          Lex███Eve███rt
user_id         pfbid0EEtyYKUZGJd3JjjjbU2fokyDV4qQAKTG7iS9ksqV...
user_url                https://www.facebook.com/lexus.everhart.9
date_created                           "2024-08-09T18:45:11.000Z"
comment_text                                Proud of you Tyler!!!
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              995  \
url             https://www.facebook.com/shanklinhvac/posts/pf...
post_id         pfbid02erggVcAEKfoqcTgF2vyzMcLTduNML2Yg9MTzUJx...
post_url        https://www.facebook.com/shanklinhvac/posts/pf...
comment_id      Y29tbWVudDoxMzIwMzA1NzYyNjA5MDU5XzUxMDMwNTUzMT...
user_name                                Mar███ou ███wn █████████
user_id         pfbid0BXxkT5vRCQpbu4UqoHNWByku1dUi67DHLbTBn5TH...
user_url        https://www.facebook.com/people/Mary-Lou-Brown...
date_created                           "2024-10-04T01:16:16.000Z"
comment_text                       I see a couple of guys I know😉
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              996  \
url             https://www.facebook.com/iccwbo/posts/pfbid02G...
post_id         pfbid02G2xUnYAtWJKsPPEAbqCD46MaDeqbpfHuUGR13Q8...
post_url        https://www.facebook.com/iccwbo/posts/pfbid02G...
comment_id      Y29tbWVudDo5NTExNTc3MjcwNTE1MjFfODY4NTMwNzY3OD...
user_name                               Abu███ar ███ahi█████████d
user_id                                           100028321385146
user_url                        https://www.facebook.com/ibngarko
date_created                           "2024-11-11T12:08:20.000Z"
comment_text                                               Good 👍
num_likes                                                     NaN
num_replies                                                   NaN
attached_files                                                NaN
video_length                                                  NaN
source_type                                      TextWithEntities
subtype                                          TextWithEntities
type                                                      Comment

                                                              997  \
url             https://www.facebook.com/shanklinhvac/posts/pf...
post_id         pfbid0UHgxHFjQpE2BujPcnV92vLb2dzihNi7n2eWHcfyg...
post_url        https://www.facebook.com/shanklinhvac/posts/pf...
comment_id      Y29tbWVudDoxMjU2MzAxNzcyMzQyNzkyXzg0NTQyMDE4MD...
user_name                                      Lat███a S███oma███
user_id         pfbid042YMD3nynfYbA4baKKXzzUem2Lj7Es8gjaksXgm3...
user_url                                                      NaN
date_created                           "2024-07-10T18:26:11.000Z"
comment_text                             Happy Birthday to all 🎂🎉
num_likes                                                     NaN

In [26]:
#Melt --> Convert columns into rows 
# wide Format --> many Columns 
# Long Format ---> Fewer Columns , more rows 
df.columns
df = df.dropna(subset=['num_likes','num_replies'])
df['num_likes'] = df['num_likes'].fillna(0)
df['num_replies'] = df['num_replies'].fillna(0)
melt_df = pd.melt(df, id_vars=['type'], value_vars=['num_likes', 'num_replies'])
print(melt_df.head())

      type   variable  value
0  Comment  num_likes    0.0
1  Comment  num_likes    0.0
2  Comment  num_likes    0.0
3  Comment  num_likes    0.0
4  Comment  num_likes    0.0

In [28]:
#Pivot = convert rows into columns 
# long Format ---> many rows 
# wide  Format --> more Columsn 
pivot_df = pd.pivot_table(melt_df, index='type', columns='variable', values='value')
print(pivot_df)

variable  num_likes  num_replies
type
Comment         0.0        1.079

In [29]:
# Merge Example 
df2=df[ ['num_replies' , 'num_likes']]
merged = pd.merge( df , df2 , on='num_replies')
print(merged.head())

                                                 url  \
0  https://www.facebook.com/verizon/posts/pfbid0z...
1  https://www.facebook.com/verizon/posts/pfbid0z...
2  https://www.facebook.com/verizon/posts/pfbid0z...
3  https://www.facebook.com/verizon/posts/pfbid0z...
4  https://www.facebook.com/verizon/posts/pfbid0z...

                                             post_id  \
0  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
1  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
2  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
3  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...
4  pfbid0zpLRka9my4ndgcCwHZeBMZ17jPM9gmzb6M5meVy9...

                                            post_url  \
0  https://www.facebook.com/verizon/posts/pfbid0z...
1  https://www.facebook.com/verizon/posts/pfbid0z...
2  https://www.facebook.com/verizon/posts/pfbid0z...
3  https://www.facebook.com/verizon/posts/pfbid0z...
4  https://www.facebook.com/verizon/posts/pfbid0z...

                                          comment_id       user_name  \
0  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...  Kat███Dav███on
1  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...  Kat███Dav███on
2  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...  Kat███Dav███on
3  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...  Kat███Dav███on
4  Y29tbWVudDozOTczNzM0OTkzNDQxNDNfOTA2NTc0NzI3Nj...  Kat███Dav███on

                                             user_id user_url  \
0  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      NaN
1  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      NaN
2  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      NaN
3  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      NaN
4  pfbid02QbSc7Zs4wR67DWEXtcGGyDdP6MjktDUBe7MHb2b...      NaN

                 date_created comment_text  num_likes_x  num_replies  \
0  "2024-01-12T13:41:08.000Z"    Joy House          0.0          1.0
1  "2024-01-12T13:41:08.000Z"    Joy House          0.0          1.0
2  "2024-01-12T13:41:08.000Z"    Joy House          0.0          1.0
3  "2024-01-12T13:41:08.000Z"    Joy House          0.0          1.0
4  "2024-01-12T13:41:08.000Z"    Joy House          0.0          1.0

  attached_files  video_length       source_type           subtype     type  \
0            NaN           NaN  TextWithEntities  TextWithEntities  Comment
1            NaN           NaN  TextWithEntities  TextWithEntities  Comment
2            NaN           NaN  TextWithEntities  TextWithEntities  Comment
3            NaN           NaN  TextWithEntities  TextWithEntities  Comment
4            NaN           NaN  TextWithEntities  TextWithEntities  Comment

   num_likes_y
0          0.0
1          0.0
2          0.0
3          0.0
4          0.0